laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('artigos', ['as' => 'artigos', 'uses' => 'HomeController@index']);
Route::get('artigos/{categoria_slug}', ['as' => 'artigos.categoria', 'uses' => 'HomeController@index']);
Route::get('artigos/{categoria_slug}/{post_slug}', ['as' => 'artigos.post', 'uses' => 'HomeController@show']);
Route::post('artigos/{categoria_slug}/{post_slug}', ['as' => 'artigos.comentario', 'uses' => 'HomeController@comentario']);
Route::get('perfil', ['as' => 'perfil', 'uses' => 'PerfilController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'ContatoController@envio']);
Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'NewsletterController@index']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::get('blog/comentarios/{comentarios}/aprovacao/{value}', 'BlogComentariosController@aprovacao');
    Route::get('blog/posts/{categorias}', 'BlogPostsController@posts');
    Route::resource('blog/categorias', 'BlogCategoriasController');
    Route::resource('blog/comentarios', 'BlogComentariosController');
    Route::resource('blog/destaques', 'BlogDestaquesController');
    Route::resource('blog', 'BlogPostsController');
    Route::resource('perfil', 'PerfilController');
    Route::resource('usuarios', 'UsuariosController');
    Route::resource('contato/recebidos', 'ContatosRecebidosController');
    Route::resource('contato', 'ContatoController');
    Route::get('newsletter/exportar', ['as' => 'painel.newsletter.exportar', 'uses' => 'NewsletterController@exportar']);
    Route::resource('newsletter', 'NewsletterController');

    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/resources/views/painel/blog/destaques/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Blog /</small> Adicionar Destaque</h2>
    </legend>

    {!! Form::open(['route' => 'painel.blog.destaques.store']) !!}

        @include('painel.blog.destaques.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@stop

laravel/resources/views/painel/blog/destaques/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('blog_categoria_id', 'Categoria') !!}
    {!! Form::select('blog_categoria_id', $categorias, '', ['class' => 'form-control select-categorias', 'placeholder' => 'Selecione']) !!}
</div>

<div class="form-group">
    {!! Form::label('blog_post_id', 'Post') !!}
    {!! Form::select('blog_post_id', [], null, ['class' => 'form-control', 'placeholder' => 'Selecione uma Categoria']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.blog.destaques.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/blog/destaques/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.blog.index') }}" class="btn btn-sm btn-default">
        &larr; Voltar para Blog
    </a>

    <legend>
        <h2>
            <small>Blog /</small> Destaques
            @if(count($destaques) < $limite)
            <a href="{{ route('painel.blog.destaques.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Destaque</a>
            @endif
        </h2>
    </legend>

    @if(!count($destaques))
    <div class="alert alert-warning" role="alert">Nenhum destaque cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Data</th>
                <th>Título</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($destaques as $destaque)
            <tr class="tr-row">
                <td>{{ $destaque->data }}</td>
                <td>{{ $destaque->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open(array('route' => array('painel.blog.destaques.destroy', $destaque->id), 'method' => 'delete')) !!}

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection